name: Build and upload binaries to release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: star-stacker
            asset_name: star-stacker-linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install external build dependencies
        run: sudo apt install -y clang libclang-dev libopencv-dev python3-opencv
      - name: Build project
        run: cd star-stacker; cargo build --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.client_payload.new_version }}
